import type { NextPage } from 'next'
import Head from 'next/head'
import Typography from '@mui/material/Typography'
import Container from '@mui/material/Container'
import Link from '@mui/material/Link'
import { Box } from '@mui/material'
import { CalcCityTax } from '../components/CalcCityTax/CalcCityTax'
import { CalcNurseryFee } from '../components/CalcNurseryFee'
import { useState } from 'react'
import { SubTitle } from '../components/Subtitle'
import { specifyLayer } from '../lib/specifyLayer'
import { calcCityTax } from '../lib/calcCityTax'

const Home: NextPage = () => {
    const [fathersIncome, setFathersIncome] = useState(0)
    const [mothersIncome, setMothersIncome] = useState(0)
    const [fathersIncomeDeduction, setFathersIncomeDeduction] = useState(0)
    const [mothersIncomeDeduction, setMothersIncomeDeduction] = useState(0)
    const [layer, setLayer] = useState(0)

    const familyCityTax =
        calcCityTax(fathersIncome, fathersIncomeDeduction, 0) +
        calcCityTax(mothersIncome, mothersIncomeDeduction, 0)

    return (
        <Container>
            <Head>
                <title>京都市保育料シミュレーター</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box component="main" sx={{ paddingTop: '15px' }}>
                <Typography
                    variant="h1"
                    sx={{
                        backgroundColor: '#622A78',
                        color: 'white',
                        padding: '20px 15px 20px 20px',
                        fontSize: '24px',
                    }}
                >
                    京都市の保育料シミュレーション
                </Typography>
                <p>
                    京都市認可保育施設の保育料を簡易シミュレーションできます。
                    計算するのは幼保無償化対象外の0~2歳の保育料です。
                    <br />
                    <br />
                    この計算結果はあくまで参考情報です。
                    <br />
                    実際の保育料徴収額は京都市より送付される保育料決定通知書等をご確認ください。
                    <br />
                    <br />
                    なお，保育料の詳細については
                    <Link href="https://www.city.kyoto.lg.jp/hagukumi/page/0000178518.html">
                        「子ども・子育て支援制度における利用者負担額（保育料）について」
                    </Link>
                    をご覧ください。
                </p>
                <SubTitle>Step1 父の情報の入力</SubTitle>
                <CalcCityTax
                    relationship="父"
                    myIncome={fathersIncome}
                    setMyIncome={setFathersIncome}
                    spouseIncome={mothersIncome}
                    setIncomeDeduction={setFathersIncomeDeduction}
                />
                <SubTitle>Step2 母の情報の入力</SubTitle>
                <CalcCityTax
                    relationship="母"
                    myIncome={mothersIncome}
                    setMyIncome={setMothersIncome}
                    spouseIncome={fathersIncome}
                    setIncomeDeduction={setMothersIncomeDeduction}
                />
                <SubTitle>Step3 保育料シミュレーション結果</SubTitle>
                <CalcNurseryFee familyCityTax={familyCityTax} />
            </Box>

            <footer></footer>
        </Container>
    )
}

export default Home
